import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

const projectRoot = path.resolve(import.meta.dirname, "..");
const args = new Map();
for (let index = 2; index < process.argv.length; index += 2) {
  args.set(process.argv[index], process.argv[index + 1]);
}

const usSource = args.get("--us");
const ukSource = args.get("--uk");
if (!usSource || !ukSource) {
  throw new Error("Usage: node scripts/generate_pronunciation_data.mjs --us <en_US.txt> --uk <britfone.csv>");
}

function normalizeTerm(value) {
  return String(value || "")
    .normalize("NFKC")
    .replace(/[’‘]/g, "'")
    .replace(/[_–—-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

function cleanIpa(value) {
  const firstVariant = String(value || "").split(/,\s+(?=\/)/)[0].trim();
  if (!firstVariant) return "";
  const withoutSlashes = firstVariant.replace(/^\/+|\/+$/g, "").trim();
  return withoutSlashes ? `/${withoutSlashes}/` : "";
}

function parseUsDictionary(filePath) {
  const entries = new Map();
  for (const line of fs.readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const [rawWord, rawIpa] = line.split("\t");
    const word = normalizeTerm(rawWord);
    const ipa = cleanIpa(rawIpa);
    if (word && ipa && !entries.has(word)) entries.set(word, ipa);
  }
  return entries;
}

function parseUkDictionary(filePath) {
  const entries = new Map();
  for (const line of fs.readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const separator = line.indexOf(",");
    if (separator < 1) continue;
    const rawWord = line.slice(0, separator).replace(/\(\d+\)$/, "");
    const rawIpa = line.slice(separator + 1).trim().replace(/\s+/g, "");
    const word = normalizeTerm(rawWord);
    const ipa = cleanIpa(rawIpa);
    if (word && ipa && !entries.has(word)) entries.set(word, ipa);
  }
  return entries;
}

function loadProjectTerms() {
  const context = { console };
  vm.createContext(context);
  const files = [
    "assets/js/vocabulary-data.js",
    "assets/js/ielts-band7-data.js",
    "assets/js/idiom-data.js"
  ];
  const source = files
    .map(file => fs.readFileSync(path.join(projectRoot, file), "utf8"))
    .join("\n") + "\nglobalThis.__terms = [...vocabularySeed, ...idiomSeed];";
  vm.runInContext(source, context);
  return context.__terms;
}

function americanSpellingCandidates(term) {
  const candidates = [term];
  const replacements = [
    [/isation$/, "ization"],
    [/ising$/, "izing"],
    [/ised$/, "ized"],
    [/ise$/, "ize"],
    [/our$/, "or"]
  ];
  replacements.forEach(([pattern, replacement]) => {
    if (pattern.test(term)) candidates.push(term.replace(pattern, replacement));
  });
  return candidates;
}

function lookupPronunciation(term, dictionary, allowAmericanSpelling = false) {
  const candidates = allowAmericanSpelling ? americanSpellingCandidates(term) : [term];
  return candidates.map(candidate => dictionary.get(candidate)).find(Boolean) || "";
}

function composePronunciation(term, dictionary, allowAmericanSpelling = false) {
  const normalized = normalizeTerm(term);
  const exact = lookupPronunciation(normalized, dictionary, allowAmericanSpelling);
  if (exact) return exact;

  const tokens = normalized.match(/[a-z]+(?:'[a-z]+)?/g) || [];
  if (tokens.length < 2) return "";
  const parts = tokens.map(token => lookupPronunciation(token, dictionary, allowAmericanSpelling));
  if (parts.some(part => !part)) return "";
  return `/${parts.map(part => part.replace(/^\/+|\/+$/g, "")).join(" ")}/`;
}

const usDictionary = parseUsDictionary(path.resolve(usSource));
const ukDictionary = parseUkDictionary(path.resolve(ukSource));
const terms = loadProjectTerms();
const pronunciationEntries = {};
const missing = [];

for (const item of terms) {
  const key = normalizeTerm(item.word);
  if (!key || pronunciationEntries[key]) continue;
  const uk = composePronunciation(key, ukDictionary);
  const us = composePronunciation(key, usDictionary, true);
  if (uk || us) pronunciationEntries[key] = { ...(uk ? { uk } : {}), ...(us ? { us } : {}) };
  else missing.push(item.word);
}

const sortedEntries = Object.fromEntries(Object.entries(pronunciationEntries).sort(([a], [b]) => a.localeCompare(b)));
const missingUnique = [...new Set(missing)];
const output = `// Generated by scripts/generate_pronunciation_data.mjs.
// UK IPA: Britfone 3.0.1 (MIT). US IPA: open-dict-data/ipa-dict en_US (MIT).
// This compact file contains only terms used by Vocab Battle. See THIRD_PARTY_NOTICES.md.
const VBPronunciation = (() => {
  const entries = ${JSON.stringify(sortedEntries, null, 2)};

  function normalize(value) {
    return String(value || "")
      .normalize("NFKC")
      .replace(/[’‘]/g, "'")
      .replace(/[_–—-]+/g, " ")
      .replace(/\\s+/g, " ")
      .trim()
      .toLowerCase();
  }

  function get(term) {
    return entries[normalize(term)] || null;
  }

  function cambridgeUrl(term) {
    const slug = normalize(term).replace(/[^a-z0-9' ]/g, "").replace(/'+/g, "").replace(/\\s+/g, "-");
    return \`https://dictionary.cambridge.org/vi/dictionary/english/\${encodeURIComponent(slug).replace(/%2D/g, "-")}\`;
  }

  return Object.freeze({ get, cambridgeUrl });
})();
`;

fs.writeFileSync(path.join(projectRoot, "assets/js/pronunciation-data.js"), output, "utf8");
console.log(JSON.stringify({
  totalTerms: new Set(terms.map(item => normalizeTerm(item.word))).size,
  generated: Object.keys(sortedEntries).length,
  withUk: Object.values(sortedEntries).filter(item => item.uk).length,
  withUs: Object.values(sortedEntries).filter(item => item.us).length,
  missingCount: missingUnique.length,
  missing: missingUnique.slice(0, 30)
}, null, 2));
